<?php
// $Id: xoops_version.php,v 1.8 2004/12/26 19:11:54 onokazu Exp $
//  ------------------------------------------------------------------------ //
//                XOOPS - PHP Content Management System                      //
//                    Copyright (c) 2000 XOOPS.org                           //
//                       <http://www.xoops.org/>                             //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //
if (!defined('XOOPS_ROOT_PATH')) {
	die('XOOPS root path not defined');	
	}
$moduleDirName = basename( dirname( __FILE__ ) ) ;

$modversion['name'] = "Contato";
$modversion['version'] = 0.1;
$modversion['description'] = "Módulo de contato";
$modversion['credits'] = "einstein@einsoft.com.br";
$modversion['author'] = 'fabricadecliques.com.br';
$modversion['nickname'] = 'einstein';
$modversion['help'] = 'page=help';
$modversion['license'] = 'GNU GPL 2.0';
$modversion['license_url'] = "www.gnu.org/licenses/gpl-2.0.html/";
$modversion['official'] = 0;
$modversion['image'] = "images/contato_logo.png";
$modversion['dirname'] = "contato";
$modversion['dirmoduleadmin'] = 'Frameworks/moduleclasses';
$modversion['icons16'] = 'Frameworks/moduleclasses/icons/16';
$modversion['icons32'] = 'Frameworks/moduleclasses/icons/32';

//about
$modversion["module_website_url"] = "http://www.fabricadecliques.com.br/";
$modversion["module_website_name"] = "Fábrica de Cliques";
$modversion["release_date"] = "17/10/2011";
$modversion["module_status"] = "Beta";
$modversion["author_website_url"] = "http://www.einsoft.com.br/";
$modversion["author_website_name"] = "Einsoft Microsistemas";
$modversion['min_php']='5.2';
$modversion['min_xoops']="2.5";

//Admin things
$modversion['hasAdmin'] = 1;

// Menu
$modversion['hasMain'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";
// Set to 1 if you want to display menu generated by system module
$modversion['system_menu'] = 1;

// Templates
$i = 1;
$modversion['templates'][$i]['file'] = 'contato_formulario.html';
$modversion['templates'][$i]['description'] = '_MI_CONTACT_TEMPLATES';


// Config categories
/*
$modversion['configcat'][1]['nameid'] = 'settings';
$modversion['configcat'][1]['name'] = '_MI_CONTACT_SETTINGS';
$modversion['configcat'][1]['description'] = '_MI_CONTACT_SETTINGS_DSC';

$modversion['configcat'][2]['nameid'] = 'general';
$modversion['configcat'][2]['name'] = '_MI_CONTACT_GEN';
$modversion['configcat'][2]['description'] = '_MI_CONTACT_GEN_DSC';
*/
// CONFIG stuff
// contact_allowsendconfirm
// contact_depttitle
$modversion['config'][1]['name'] = 'contato_email';
$modversion['config'][1]['title'] = 'E-mail';
$modversion['config'][1]['description'] = 'E-mail para receber as mensagens';
$modversion['config'][1]['formtype'] = 'textbox';
$modversion['config'][1]['valuetype'] = 'text';
$modversion['config'][1]['default'] = _MI_CONTATO_DEPTTITLEDEFAULT;
$modversion['config'][1]['category'] = 'general';

// contact_icq
/*
$modversion['config'][2]['name'] = 'contact_icq';
$modversion['config'][2]['title'] = '_MI_CONTACT_GETICQ';
$modversion['config'][2]['description'] = '_MI_CONTACT_GETICQDSC';
$modversion['config'][2]['formtype'] = 'yesno';
$modversion['config'][2]['valuetype'] = 'int';
$modversion['config'][2]['default'] = 0;
$modversion['config'][2]['category'] = 'settings';
*/
// contact_url
/*
$modversion['config'][3]['name'] = 'contact_url';
$modversion['config'][3]['title'] = '_MI_CONTACT_GETURL';
$modversion['config'][3]['description'] = '_MI_CONTACT_GETURLDSC';
$modversion['config'][3]['formtype'] = 'yesno';
$modversion['config'][3]['valuetype'] = 'int';
$modversion['config'][3]['default'] = 0;
$modversion['config'][3]['category'] = 'settings';
*/
?>